version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: robot_world
      POSTGRES_USER: robot
      POSTGRES_PASSWORD: world
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
